spring:
  data:
    mongodb:
      authentication-database: admin
      username: 
      password: 
      database: myhealth 
      port: 27017
      host: localhost

###############################################
########### MYHEALTH PROPERTIES ###############
###############################################

