spring:
  data:
    mongodb:
      authentication-database: test
      username: admin
      password: admin
      database: myhealth 
      port: 27017
      host: localhost

###############################################
########### MYHEALTH PROPERTIES ###############
###############################################

