server:  
  servlet:
    context-path: /myhealth

spring:
  application:
    name: MyHealth
  profiles:
    active: dev
  #jackson:
    #default-property-inclusion: NON_NULL
    #serialization:
      #write-dates-as-timestamps: true
  messages:
    basename: i18n/common, i18n/myhealth
    encoding: UTF-8
    use-code-as-default-message: true
    
###############################################
############# MYHEALTH PROPERTIES #############
###############################################

myhealth:
  dateformat: dd/MM/yyyy