spring:
  data:
    mongodb:
      database: myhealth 
      port: 27017
      host: localhost

###############################################
########### MYHEALTH PROPERTIES ###############
###############################################

